# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

dist: trusty
language: python

addons:
  sonarcloud:
    organization: "se-jaeger-github"
    token:
      secure: "uDWDfG0OvfYyUskozelzWMWApzLOaDEJ20FL+QB83pjazi1cyzqX1Jaf1jiXn7GHmHLIZnv6uLNlBp91xXCGi5/ppIRf/bsrRNtBWVsjpAUFd7XP375Q73B87spxtPk2u8rYpS7QjYy/JTwhHsuKCSax/sGdnieGFRovwjAepuFr1xCEprx4AIms3rWJ1feCfHeXgEdyhm36NqwwKZA3h4msbKavBz9ic4lFl2dUtPfwjnTtZvxLEbMPYxglr7d1MziOjFSftqjXCDAwnxqrCG4oqYygy096iM8dfbdqUJhHz7k4/CLWgdjHnz5D9FydkDsnRawdgOCKhlqIWehYMw3hvcm7afvhfmIeljsaBpTl82BF9qmUFsCs2Ai++JSKKPcEMMoFQ7IX0iPfMShM23f9w0OprceZByRym23kzKP5Heat6QWOPgnZKqHNZrOTxgvbdFRU4wtOtvUoAM8rbguCTOckqUJ6m9pJLPLBpbpXomFgGpQEXf6kt0kC0oVc33KY1cVS/PGOvw6CIraRsgQVcdM1fYneymEFA/SNbT4iaogLkCHB4ESw0/Mz0Xh1z4Y1q7tQuqsT9J2tGWO2/2a3xtxVaS4qBZpAryoWkSwtkbRfxgLordIy1q9+DRIj91k6EYoeZ7u8mErg4aJF1EY4XR07N1XfJnzghbWqEoY="

virtualenv:
  system_site_packages: true

matrix:
  include:
    - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"

install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt

before_script:
  - git config --global user.email "se.jaeger@web.de"
  - git config --global user.name "Sebastian Jäger"

script:
  - python setup.py test
  - sonar-scanner

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi

after_script:
  - travis-cleanup

cache:
  pip: true
  directories:
    - $HOME/miniconda